# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nothing <- function(matrix) {
    .Call('Qubic_nothing', PACKAGE = 'Qubic', matrix)
}

qubic <- function(matrix) {
    .Call('Qubic_qubic', PACKAGE = 'Qubic', matrix)
}

