# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a qualitative discrete matrix for a given gene expression matrix
#'
#' \code{qudiscretize} delivers a discrete matrix. It is useful if we just want
NULL

#'
#' @details
#' \code{qudiscretize} convert a given gene expression matrix to a discrete
NULL

#' @backref src/rcpp_qubic.cpp
.scqubic_d <- function(matrix, c, o, f, k, P, S, C, verbose) {
    .Call('_QUBIC_scqubic_d', PACKAGE = 'QUBIC', matrix, c, o, f, k, P, S, C, verbose)
}

#' @backref src/rcpp_qubic.cpp
.qubic_d <- function(matrix, c, o, f, k, P, S, C, verbose) {
    .Call('_QUBIC_qubic_d', PACKAGE = 'QUBIC', matrix, c, o, f, k, P, S, C, verbose)
}

#' @backref src/rcpp_qubic.cpp
.scqubic_de <- function(matrix, c, verbose, RowxNumber, NumberxCol) {
    .Call('_QUBIC_scqubic_de', PACKAGE = 'QUBIC', matrix, c, verbose, RowxNumber, NumberxCol)
}

#' @backref src/rcpp_qubic.cpp
.qubic_de <- function(matrix, c, verbose, RowxNumber, NumberxCol) {
    .Call('_QUBIC_qubic_de', PACKAGE = 'QUBIC', matrix, c, verbose, RowxNumber, NumberxCol)
}

#' @backref src/rcpp_qubic.cpp
.scqubic_dw <- function(matrix, c, o, f, k, P, S, C, verbose, weight) {
    .Call('_QUBIC_scqubic_dw', PACKAGE = 'QUBIC', matrix, c, o, f, k, P, S, C, verbose, weight)
}

#' @backref src/rcpp_qubic.cpp
.qubic_dw <- function(matrix, c, o, f, k, P, S, C, verbose, weight) {
    .Call('_QUBIC_qubic_dw', PACKAGE = 'QUBIC', matrix, c, o, f, k, P, S, C, verbose, weight)
}

#'
#' @usage qudiscretize(x, r = 1L, q = 0.06)
#' @inheritParams QUBIC
#'
#' @return A qualitative discrete matrix
#'
#' @name qudiscretize
#'
#' @aliases qudiscretize qdiscretize
#'
#' @examples
#' # Qualitative discretize yeast microarray data
#' data(BicatYeast)
#' qudiscretize(BicatYeast[1:7, 1:5])
#'
#' @seealso \code{\link{QUBIC}} \code{\link{discretize}}
#' @backref src/rcpp_qubic.cpp
qudiscretize <- function(x, r = 1L, q = 0.06) {
    .Call('_QUBIC_qudiscretize', PACKAGE = 'QUBIC', x, r, q)
}

